//! Compiler aliases for the single machine-owned FrameProgram v1 contract.

pub use wrela_machine::pixels::{
    FRAME_PROGRAM_DIGEST_BYTES_V1, FRAME_PROGRAM_DIGEST_OFFSET_V1,
    FRAME_PROGRAM_FORMAL_REVISION_STR_V1, FRAME_PROGRAM_FORMAL_REVISION_V1,
    FRAME_PROGRAM_HEADER_BYTES_V1, FRAME_PROGRAM_HOT_ALIGNMENT_V1,
    FRAME_PROGRAM_IMMEDIATE_BYTES_V1, FRAME_PROGRAM_MAGIC_V1, FRAME_PROGRAM_MAX_BYTES_V1,
    FRAME_PROGRAM_NUMERIC_REVISION_V1, FRAME_PROGRAM_PROFILE_REVISION_V1,
    FRAME_PROGRAM_RECORD_BYTES_V1, FRAME_PROGRAM_TABLE_ALIGNMENT_V1, FRAME_PROGRAM_TABLE_BYTES_V1,
    FRAME_PROGRAM_VERSION_V1, FrameProgramHeaderV1, FrameProgramImmediateV1, FrameProgramRecordV1,
    FrameProgramTableKindV1, FrameProgramTableV1,
};
