//! Image runtime config generator (plans/M11.md item D, decisions 700–702 /
//! 709 / 760–769).
//!
//! After `@image` evaluation + placement, the compiler pretty-prints a
//! hidden facts-only module (`core.__image_runtime`) as source text and
//! feeds it through the ordinary front end. No AST synthesis, no loops or
//! decisions in the generated text — consts, one `@layout(runtime)` type,
//! and one `@placed` static at `RTDATA_BASE`.

use crate::layout::RuntimeTables;
use crate::syntax::ast::Module;
use crate::syntax::{lexer, parser};
use wrela_machine::layout::RTDATA_BASE;

/// Hidden module address (decision 701). Loader key is `["core", "__image_runtime"]`;
/// the file declares plain `module __image_runtime` like every other `core.*` file.
pub const MODULE_PATH: &[&str] = &["__image_runtime"];

/// Dotted address used in TypedProgram / report maps.
pub const MODULE_ADDR: &str = "core.__image_runtime";

/// Report `Input path=` spelling for the generated module (decision 701 / 764).
pub const GENERATED_INPUT_PATH: &str = "<generated>";

/// Dump stage name (decision 701).
pub const DUMP_STAGE: &str = "rtconfig";

/// Pretty-print the facts-only config module for `tables`.
///
/// `tables.cores` must already reflect `PlacementTable.cores` (call
/// [`RuntimeTables::stripe_for_cores`] first). Emits `const N_CORES: usize =
/// <tables.cores>` with that exact spelling (decision 709 / 761).
pub fn generate(tables: &RuntimeTables) -> String {
    let mut out = String::new();
    out.push_str("module __image_runtime\n");
    out.push_str("\n");
    out.push_str("# generated by wrela; do not edit (dump --stage=rtconfig)\n");
    out.push_str("\n");
    push_const(&mut out, "N_CORES", tables.cores);
    push_const(&mut out, "N_TURNS", tables.n_turns as usize);
    push_const(&mut out, "N_ACTORS", tables.actors.len());
    push_const(&mut out, "N_DRIVERS", tables.drivers.len());
    push_const(
        &mut out,
        "READY_QUEUE_CAPACITY",
        tables.ready_queue_capacity as usize,
    );
    push_const(
        &mut out,
        "GROUP_ARENA_CAPACITY",
        tables.group_arena_capacity as usize,
    );
    push_const(&mut out, "TURN_STRIDE", tables.turn_stride as usize);
    push_const(&mut out, "RTDATA_BYTES", tables.total_bytes as usize);
    out.push('\n');
    // Opaque overlay sized to the live `rtdata` reservation. Structured
    // fields (turns / mailboxes / match ladders) land as E–J migrate
    // emitters; item D pins the counts and the placed base (decision 762).
    out.push_str("@layout(runtime, endian=little)\n");
    out.push_str("struct RuntimeTables:\n");
    out.push_str("    bytes: [u8; RTDATA_BYTES]\n");
    out.push('\n');
    out.push_str(&format!("@placed({RTDATA_BASE:#x})\n"));
    out.push_str("static RT: RuntimeTables\n");
    out
}

fn push_const(out: &mut String, name: &str, value: usize) {
    out.push_str(&format!("pub const {name}: usize = {value}\n"));
}

/// Lex + parse generated text into a `Module` (ordinary front end).
pub fn parse_generated(text: &str) -> Result<Module, String> {
    let tokens = lexer::lex(text)
        .map_err(|e| format!("rtconfig lex: {} at {}:{}", e.message, e.line, e.col))?;
    parser::parse(tokens)
        .map_err(|e| format!("rtconfig parse: {} at {}:{}", e.message, e.line, e.col))
}

/// True when `text` contains a forbidden facts-only keyword as a whole word
/// (decision 702 / 763). Deliberately dumb: substring-in-comment would also
/// fail, which is fine — the generator never emits those words.
pub fn contains_forbidden_construct(text: &str) -> bool {
    for word in ["while", "for", "async", "@actor"] {
        if text
            .split(|c: char| !c.is_ascii_alphanumeric() && c != '@')
            .any(|t| t == word)
        {
            return true;
        }
    }
    false
}

/// Insert `Input path=<generated> sha256=…` after the last existing
/// `Input path=` line in a rendered report, or after the quota block if
/// none. Stable across runs (decision 764).
pub fn insert_generated_input_line(report: &mut String, digest: &str) {
    let line = format!("  Input path={GENERATED_INPUT_PATH} sha256={digest}\n");
    let mut last_input_end: Option<usize> = None;
    for (idx, _) in report.match_indices("  Input path=") {
        let end = report[idx..]
            .find('\n')
            .map(|n| idx + n + 1)
            .unwrap_or(report.len());
        last_input_end = Some(end);
    }
    if let Some(at) = last_input_end {
        report.insert_str(at, &line);
        return;
    }
    // No inputs (degenerate): after the last Quota line.
    let mut after_quota: Option<usize> = None;
    for (idx, _) in report.match_indices("  Quota ") {
        let end = report[idx..]
            .find('\n')
            .map(|n| idx + n + 1)
            .unwrap_or(report.len());
        after_quota = Some(end);
    }
    if let Some(at) = after_quota {
        report.insert_str(at, &line);
    } else {
        report.push_str(&line);
    }
}

/// Batch-2 front end (decision 704 / 723 / 765): parse generated text +
/// unstripped `runtime.wr`, run the ordinary `check_program_typed`. Does
/// not merge into the caller's program map — item D keeps the generated
/// module out of layout/`PlacedStatic` until E–J need `RT` (narrow seam).
/// Fails closed if the pair does not typecheck.
pub fn typecheck_batch2(generated_text: &str) -> Result<(), String> {
    if contains_forbidden_construct(generated_text) {
        return Err(
            "error[build]: generated rtconfig contains a forbidden construct \
             (while/for/async/@actor); facts-only rule (plans/M11.md decision 702)"
                .to_string(),
        );
    }
    let gen_module = parse_generated(generated_text)?;
    let (runtime_key, runtime_loaded) =
        crate::loader::load_runtime_module_with_image_runtime_import().map_err(|e| match e {
            crate::loader::LoadError::Lex(err) => {
                format!("error[lex]: {} at {}:{}", err.message, err.line, err.col)
            }
            crate::loader::LoadError::Parse(err) => {
                format!("error[parse]: {} at {}:{}", err.message, err.line, err.col)
            }
            crate::loader::LoadError::Build(err) => format!(
                "error[{}]: {} at {}:{}",
                err.category, err.message, err.line, err.col
            ),
        })?;
    let gen_key: Vec<String> = crate::loader::IMAGE_RUNTIME_MODULE_KEY
        .iter()
        .map(|s| (*s).to_string())
        .collect();
    let mut modules = std::collections::BTreeMap::new();
    modules.insert(gen_key.clone(), gen_module);
    modules.insert(runtime_key.clone(), runtime_loaded.module);
    let mut paths = std::collections::BTreeMap::new();
    paths.insert(gen_key, GENERATED_INPUT_PATH.to_string());
    paths.insert(runtime_key, runtime_loaded.file.display().to_string());
    crate::sema::check_program_typed(&modules, &paths).map_err(|e| {
        format!(
            "error[{}]: {} at {}:{}",
            e.category, e.message, e.line, e.col
        )
    })?;
    Ok(())
}

/// Generate + batch-2 typecheck for a laid-out image's runtime tables.
/// Returns the generated source text.
pub fn generate_and_typecheck(tables: &RuntimeTables) -> Result<String, String> {
    let text = generate(tables);
    typecheck_batch2(&text)?;
    Ok(text)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::RuntimeTables;

    fn sample_tables(cores: usize) -> RuntimeTables {
        let mut t = RuntimeTables {
            n_turns: 3,
            turn_stride: 128,
            ready_queue_capacity: 4,
            group_arena_capacity: 0,
            total_bytes: 1024,
            cores: 1,
            ..RuntimeTables::default()
        };
        t.stripe_for_cores(cores);
        t
    }

    #[test]
    fn n_cores_spelling_and_values() {
        let one = generate(&sample_tables(1));
        assert!(
            one.contains("pub const N_CORES: usize = 1\n"),
            "single-core must spell N_CORES exactly; got:\n{one}"
        );
        let three = generate(&sample_tables(3));
        assert!(
            three.contains("pub const N_CORES: usize = 3\n"),
            "cross-core must spell N_CORES exactly; got:\n{three}"
        );
    }

    #[test]
    fn placed_uses_rtdata_base_literal() {
        let text = generate(&sample_tables(1));
        assert!(
            text.contains(&format!("@placed({RTDATA_BASE:#x})\n")),
            "expected @placed at RTDATA_BASE; got:\n{text}"
        );
        assert!(!text.contains("@placed(RTDATA_BASE)"));
    }

    #[test]
    fn facts_only_forbids_control_and_actors() {
        let text = generate(&sample_tables(1));
        assert!(
            !contains_forbidden_construct(&text),
            "generator emitted a forbidden construct:\n{text}"
        );
        assert!(contains_forbidden_construct("while true:\n    return\n"));
        assert!(contains_forbidden_construct("for x in xs:\n    return\n"));
        assert!(contains_forbidden_construct("async fn f():\n    return\n"));
        assert!(contains_forbidden_construct(
            "@actor\nstruct A:\n    x: u64\n"
        ));
    }

    #[test]
    fn generate_is_deterministic_across_two_runs() {
        let tables = sample_tables(1);
        let a = generate(&tables);
        let b = generate(&tables);
        assert_eq!(a, b);
    }

    #[test]
    fn generated_text_parses() {
        let text = generate(&sample_tables(2));
        let module = parse_generated(&text).expect("parse");
        assert_eq!(module.path, vec!["__image_runtime".to_string()]);
    }
}
